/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package farmasalud.view;

import Controller.ControllerCitasPaciente;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;
import model.Persona;
import model.Paciente;
import model.Medico;
import model.Cita;
import Controller.ControllerCitas;
import com.toedter.calendar.JDateChooser;
import dao.CitaDAO;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Maria liz
 */
public class DialogModificar extends javax.swing.JDialog {
private JTable tablaCitasPacienteExterna;

  
    public DialogModificar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
                initComponents();
         
        ControllerCitasPaciente controller = ControllerCitasPaciente.getInstance();

        controller.setTxtIdCita(txtIdCita2);
        controller.setJDateFechaCita(jDateChooserCita);
        controller.setCboHoraCita(cboHoraCita2);
        controller.setCboMotivoCita(cboMotivoCita2);
        controller.setCboTipoCita(cboTipoCita2);
        controller.setCboEstado(lblEstadoCita2);
            lblEstadoCita2.removeAllItems();
    lblEstadoCita2.addItem("PROGRAMADA");
    lblEstadoCita2.setSelectedIndex(0);
    lblEstadoCita2.setEnabled(false);
        controller.cargarSalasEnComboBox(cboConsultorio2);
        controller.cargarSedesEnComboBox(cboSede2);
        controller.setCboSede(cboSede2);
        controller.setCboMedico(cboMedico2);
        controller.setLblEspecialidadMedico(lblEspecialidadMedico2);
        controller.setLblNombre(lblNombrePaciente2);
        controller.setLblApellido(lblApellidoPaciente2);
        controller.setLblEmail(lblEmail2);
        controller.setLblDocumento(lblDocumentoPaciente2);
        controller.setCLblEps(lblEps2);
        controller.setCboConsultorio(cboConsultorio2);
    }

public void cargarDatosDesdeFilaSeleccionada(JTable table, int fila) {
    if (table == null || fila < 0 || fila >= table.getRowCount()) {
        JOptionPane.showMessageDialog(this, "Seleccione una cita válida", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    DefaultTableModel model = (DefaultTableModel) table.getModel();
    ControllerCitasPaciente controller = ControllerCitasPaciente.getInstance();

    String documentoPaciente = model.getValueAt(fila, 0).toString();
    controller.cargarYPersistirPaciente(documentoPaciente); 

    controller.cargarSalasEnComboBox(cboConsultorio2);
    controller.cargarSedesEnComboBox(cboSede2);

  
    lblDocumentoPaciente2.setText(documentoPaciente);
    lblNombrePaciente2.setText(model.getValueAt(fila, 1).toString());
    lblApellidoPaciente2.setText(model.getValueAt(fila, 2).toString());
    lblEps2.setText(model.getValueAt(fila, 3).toString());
    lblEmail2.setText(model.getValueAt(fila, 4).toString());


    txtIdCita2.setText(model.getValueAt(fila, 5).toString());
    cboHoraCita2.setSelectedItem(model.getValueAt(fila, 6).toString());
    cboMotivoCita2.setSelectedItem(model.getValueAt(fila, 7).toString());

    Object fechaObj = model.getValueAt(fila, 8);
    if (fechaObj instanceof LocalDate fechaLocal) {
        Date fecha = Date.from(fechaLocal.atStartOfDay(ZoneId.systemDefault()).toInstant());
        jDateChooserCita.setDate(fecha);
    } else if (fechaObj instanceof Date fechaDate) {
        jDateChooserCita.setDate(fechaDate);
    } else {
        jDateChooserCita.setDate(null);
    }

    cboTipoCita2.setSelectedItem(model.getValueAt(fila, 9).toString());
    cboConsultorio2.setSelectedItem(model.getValueAt(fila, 10).toString());
    lblEstadoCita2.setSelectedItem(model.getValueAt(fila, 11).toString());

    String nombreMedico = model.getValueAt(fila, 12).toString() + " " + model.getValueAt(fila, 13).toString();
    cboMedico2.setSelectedItem(nombreMedico.trim());

    lblEspecialidadMedico2.setText(model.getValueAt(fila, 14).toString());
    cboSede2.setSelectedItem(model.getValueAt(fila, 15).toString());
}

    public void setTablaCitasPaciente(JTable tabla) {
    this.tablaCitasPacienteExterna = tabla;
}


  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblNombrePaciente2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblApellidoPaciente2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblDocumentoPaciente2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        lblEmail2 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel13 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        lblEspecialidadMedico2 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        cboMedico2 = new javax.swing.JComboBox<>();
        cboSede2 = new javax.swing.JComboBox<>();
        cboConsultorio2 = new javax.swing.JComboBox<>();
        cboTipoCita2 = new javax.swing.JComboBox<>();
        cboMotivoCita2 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        lblEstadoCita2 = new javax.swing.JComboBox<>();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        cboHoraCita2 = new javax.swing.JComboBox<>();
        jSeparator13 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jDateChooserCita = new com.toedter.calendar.JDateChooser();
        txtIdCita2 = new javax.swing.JTextField();
        lblEps2 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Nombre ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 81, 26));
        jPanel2.add(lblNombrePaciente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 180, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Apellido");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 90, 26));

        jSeparator1.setBackground(new java.awt.Color(28, 43, 110));
        jSeparator1.setForeground(new java.awt.Color(28, 43, 110));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 170, 10));
        jPanel2.add(lblApellidoPaciente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 170, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Documento");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 100, 30));

        jSeparator2.setBackground(new java.awt.Color(28, 43, 110));
        jSeparator2.setForeground(new java.awt.Color(28, 43, 110));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 170, 10));
        jPanel2.add(lblDocumentoPaciente2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 170, 30));

        jSeparator3.setBackground(new java.awt.Color(28, 43, 110));
        jSeparator3.setForeground(new java.awt.Color(28, 43, 110));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 170, 10));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Consultorio");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 100, 30));

        jSeparator4.setBackground(new java.awt.Color(28, 43, 110));
        jSeparator4.setForeground(new java.awt.Color(28, 43, 110));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 170, 10));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Sede");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 90, 20));

        jSeparator5.setBackground(new java.awt.Color(28, 43, 110));
        jSeparator5.setForeground(new java.awt.Color(28, 43, 110));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 170, 10));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setText("Tipo Cita");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 100, 20));

        jSeparator6.setBackground(new java.awt.Color(28, 43, 110));
        jSeparator6.setForeground(new java.awt.Color(28, 43, 110));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 170, 10));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Motivo Cita");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 110, 30));

        jSeparator7.setBackground(new java.awt.Color(28, 43, 110));
        jSeparator7.setForeground(new java.awt.Color(28, 43, 110));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 423, 170, 10));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Telefono");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, -1, -1));
        jPanel2.add(lblEmail2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 160, 30));

        jSeparator8.setBackground(new java.awt.Color(28, 43, 110));
        jSeparator8.setForeground(new java.awt.Color(28, 43, 110));
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 117, 170, 10));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Eps");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 60, 30));

        jSeparator9.setBackground(new java.awt.Color(28, 43, 110));
        jSeparator9.setForeground(new java.awt.Color(28, 43, 110));
        jPanel2.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 170, 170, 10));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setText("Medico");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 80, 30));

        jSeparator10.setBackground(new java.awt.Color(28, 43, 110));
        jSeparator10.setForeground(new java.awt.Color(28, 43, 110));
        jPanel2.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 230, 170, 10));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Especialidad");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 110, -1));
        jPanel2.add(lblEspecialidadMedico2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 150, 40));

        jSeparator11.setBackground(new java.awt.Color(28, 43, 110));
        jSeparator11.setForeground(new java.awt.Color(28, 43, 110));
        jPanel2.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 280, 160, 10));

        jPanel2.add(cboMedico2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 170, 40));

        cboSede2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboSede2ActionPerformed(evt);
            }
        });
        jPanel2.add(cboSede2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 170, 40));

        jPanel2.add(cboConsultorio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 170, 40));

        cboTipoCita2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccione>", "Prioritaria", "Regular", "Control" }));
        jPanel2.add(cboTipoCita2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 170, 40));

        cboMotivoCita2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccionar>", "Control", "Seguimiento", "Prevencion", "Sintomas Agudos", "Enfermedad Cronica", "Problemas Especificos" }));
        jPanel2.add(cboMotivoCita2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 170, 40));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Estado");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 100, 30));

        lblEstadoCita2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccione>", "PROGRAMADA", "COMPLETADA", "CANCELADA" }));
        jPanel2.add(lblEstadoCita2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, 170, 40));

        jSeparator12.setBackground(new java.awt.Color(28, 43, 110));
        jSeparator12.setForeground(new java.awt.Color(28, 43, 110));
        jPanel2.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 170, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("Hora Cita");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, -1, -1));

        cboHoraCita2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Seleccione>", "07:00", "07:30", "08:00", "08:30", "09:00", "09:30", "10:00", "10:30", "11:00", "11:30", "12:00", "12:30", "01:00", "01:30", "02:00", "02:30", "03:00", "03:30", "04:00", "04:30", "05:00" }));
        jPanel2.add(cboHoraCita2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, 170, 40));

        jSeparator13.setBackground(new java.awt.Color(28, 43, 110));
        jSeparator13.setForeground(new java.awt.Color(28, 43, 110));
        jPanel2.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 380, 170, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Fecha Cita ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 90, -1));

        jDateChooserCita.setBackground(new java.awt.Color(28, 43, 110));
        jPanel2.add(jDateChooserCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 150, 30));
        jPanel2.add(txtIdCita2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, -1, -1));
        jPanel2.add(lblEps2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 170, 40));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("Id Cita");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 70, -1));

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel2.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 590, 520));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cboSede2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboSede2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboSede2ActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
    if (tablaCitasPacienteExterna != null) {
        ControllerCitasPaciente.getInstance().actualizarCitaDesdeFormulario(tablaCitasPacienteExterna);
        this.dispose(); // cierra el diálogo después de actualizar
    } else {
        JOptionPane.showMessageDialog(this, "No se vinculó correctamente la tabla de citas", "Error", JOptionPane.ERROR_MESSAGE);
    } 
    }//GEN-LAST:event_btnModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogModificar dialog = new DialogModificar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cboConsultorio2;
    private javax.swing.JComboBox<String> cboHoraCita2;
    private javax.swing.JComboBox<String> cboMedico2;
    private javax.swing.JComboBox<String> cboMotivoCita2;
    private javax.swing.JComboBox<String> cboSede2;
    private javax.swing.JComboBox<String> cboTipoCita2;
    private com.toedter.calendar.JDateChooser jDateChooserCita;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblApellidoPaciente2;
    private javax.swing.JLabel lblDocumentoPaciente2;
    private javax.swing.JLabel lblEmail2;
    private javax.swing.JLabel lblEps2;
    private javax.swing.JLabel lblEspecialidadMedico2;
    private javax.swing.JComboBox<String> lblEstadoCita2;
    private javax.swing.JLabel lblNombrePaciente2;
    private javax.swing.JTextField txtIdCita2;
    // End of variables declaration//GEN-END:variables
}
