/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package farmasalud.view;

import Controller.ControllerCitasPaciente;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Maria liz
 */
public class DialogCancelar2 extends javax.swing.JDialog {
private JTable tablaCitasPacienteExterna;

    /**
     * Creates new form DialogCancelar2
     */
    public DialogCancelar2(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public void mostrarDatosCitaEnLabels(JTable table, int fila) {
    if (table == null || fila < 0 || fila >= table.getRowCount()) {
        JOptionPane.showMessageDialog(this, "Seleccione una cita válida", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    DefaultTableModel model = (DefaultTableModel) table.getModel();

    lblDocumento3.setText(model.getValueAt(fila, 0).toString());
    lblNombrePaciente3.setText(model.getValueAt(fila, 1).toString());
    lblApellidoPaciente3.setText(model.getValueAt(fila, 2).toString());
    lblEps.setText(model.getValueAt(fila, 3).toString());
    lblTelefono.setText(model.getValueAt(fila, 4).toString());

    lblIdCita3.setText(model.getValueAt(fila, 5).toString());
    lblHoraCita3.setText(model.getValueAt(fila, 6).toString());
    lblMotivoCita3.setText(model.getValueAt(fila, 7).toString());
    lblFechaCita3.setText(model.getValueAt(fila, 8).toString());  // Si quieres formato bonito, conviértelo
    lblTipoCita3.setText(model.getValueAt(fila, 9).toString());

    lblConsultorio3.setText(model.getValueAt(fila, 10).toString());
    lblEstado3.setText(model.getValueAt(fila, 11).toString());

    lblMedico3.setText(model.getValueAt(fila, 12).toString());
    lblEspecialidad3.setText(model.getValueAt(fila, 14).toString());

    lblSede3.setText(model.getValueAt(fila, 15).toString());
}
  public void setTablaCitasPaciente(JTable tabla) {
    this.tablaCitasPacienteExterna = tabla;
}
  private void cancelarCitaSeleccionada() {
    String idCita = lblIdCita3.getText();

    if (idCita == null || idCita.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "ID de cita no válido", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    int confirm = JOptionPane.showConfirmDialog(this,
            "¿Está seguro que desea cancelar esta cita?",
            "Confirmación", JOptionPane.YES_NO_OPTION);

    if (confirm == JOptionPane.YES_OPTION) {
        boolean exito = ControllerCitasPaciente.getInstance().cancelarCitaPorId(idCita);

        if (exito) {
            JOptionPane.showMessageDialog(this, "Cita cancelada correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);

            // Actualiza el valor en la tabla visual directamente si se requiere
            if (tablaCitasPacienteExterna != null) {
                int fila = tablaCitasPacienteExterna.getSelectedRow();
                if (fila != -1) {
                    tablaCitasPacienteExterna.setValueAt("CANCELADA", fila, 11); // Columna estado
                }
            }

            dispose(); // Cierra el diálogo
        } else {
            JOptionPane.showMessageDialog(this, "No se pudo cancelar la cita", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblFechaCita3 = new javax.swing.JLabel();
        lblNombrePaciente3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblApellidoPaciente3 = new javax.swing.JLabel();
        lblDocumento3 = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblEps = new javax.swing.JLabel();
        lblIdCita3 = new javax.swing.JLabel();
        lblConsultorio3 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        lblTipoCita3 = new javax.swing.JLabel();
        lblMotivoCita3 = new javax.swing.JLabel();
        lblMedico3 = new javax.swing.JLabel();
        lblEspecialidad3 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        lblHoraCita3 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        lblSede3 = new javax.swing.JLabel();
        btnCancelar2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        lblEstado3 = new javax.swing.JLabel();
        jSeparator14 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Nombre  ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 90, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Apellido ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 90, 30));

        lblFechaCita3.setText("jLabel3");
        jPanel1.add(lblFechaCita3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 140, 40));

        lblNombrePaciente3.setText("jLabel4");
        jPanel1.add(lblNombrePaciente3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 140, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Documento ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 100, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Eps");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Telefono");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Fecha Cita ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Id Cita ");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 365, 70, 30));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setText("Consultorio");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, -1, -1));

        lblApellidoPaciente3.setText("jLabel12");
        jPanel1.add(lblApellidoPaciente3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 120, 40));

        lblDocumento3.setText("jLabel13");
        jPanel1.add(lblDocumento3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 130, 40));

        lblTelefono.setText("jLabel14");
        jPanel1.add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 140, 30));

        jLabel15.setText("Estado Cita");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 90, 30));

        lblEps.setText("jLabel16");
        jPanel1.add(lblEps, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 150, 40));

        lblIdCita3.setText("jLabel17");
        jPanel1.add(lblIdCita3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 140, 40));

        lblConsultorio3.setText("jLabel18");
        jPanel1.add(lblConsultorio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, 100, 30));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setText("Tipo Cita ");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel20.setText("Motivo Cita ");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, -1, -1));

        lblTipoCita3.setText("jLabel21");
        jPanel1.add(lblTipoCita3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 140, 50));

        lblMotivoCita3.setText("jLabel22");
        jPanel1.add(lblMotivoCita3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 106, 130, 40));

        lblMedico3.setText("jLabel23");
        jPanel1.add(lblMedico3, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 146, 130, 50));

        lblEspecialidad3.setText("jLabel24");
        jPanel1.add(lblEspecialidad3, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 206, 120, 50));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel25.setText("Medico");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 170, -1, -1));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel26.setText("Especialidad");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, -1, -1));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel27.setText("Hora Cita");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, -1, -1));

        lblHoraCita3.setText("jLabel28");
        jPanel1.add(lblHoraCita3, new org.netbeans.lib.awtextra.AbsoluteConstraints(375, 276, 150, 40));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel29.setText("Sede");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, -1, -1));

        lblSede3.setText("jLabel30");
        jPanel1.add(lblSede3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 150, 40));

        btnCancelar2.setText("Cancelar ");
        btnCancelar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 510, -1, 30));

        jPanel2.setBackground(new java.awt.Color(28, 43, 110));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 70));

        jSeparator1.setBackground(new java.awt.Color(28, 43, 110));
        jSeparator1.setForeground(new java.awt.Color(28, 43, 110));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 140, 10));

        jSeparator2.setBackground(new java.awt.Color(28, 43, 110));
        jSeparator2.setForeground(new java.awt.Color(28, 43, 110));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 140, 10));

        jSeparator3.setBackground(new java.awt.Color(28, 43, 110));
        jSeparator3.setForeground(new java.awt.Color(28, 43, 110));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 130, 10));

        jSeparator4.setBackground(new java.awt.Color(28, 43, 110));
        jSeparator4.setForeground(new java.awt.Color(28, 43, 110));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 150, 10));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 333, 150, 10));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 143, 130, 10));
        jPanel1.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 130, 20));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 130, 20));
        jPanel1.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 150, 10));
        jPanel1.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 150, 10));
        jPanel1.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, 140, 10));
        jPanel1.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 393, 160, 10));
        jPanel1.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, 150, 10));

        lblEstado3.setText("jLabel3");
        jPanel1.add(lblEstado3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 430, 150, 40));
        jPanel1.add(jSeparator14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 160, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar2ActionPerformed
         cancelarCitaSeleccionada();  // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelar2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogCancelar2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogCancelar2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogCancelar2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogCancelar2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogCancelar2 dialog = new DialogCancelar2(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lblApellidoPaciente3;
    private javax.swing.JLabel lblConsultorio3;
    private javax.swing.JLabel lblDocumento3;
    private javax.swing.JLabel lblEps;
    private javax.swing.JLabel lblEspecialidad3;
    private javax.swing.JLabel lblEstado3;
    private javax.swing.JLabel lblFechaCita3;
    private javax.swing.JLabel lblHoraCita3;
    private javax.swing.JLabel lblIdCita3;
    private javax.swing.JLabel lblMedico3;
    private javax.swing.JLabel lblMotivoCita3;
    private javax.swing.JLabel lblNombrePaciente3;
    private javax.swing.JLabel lblSede3;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTipoCita3;
    // End of variables declaration//GEN-END:variables
}
