/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package farmasalud.view;

/**
 *
 * @author Maria liz
 */
public class DialogOrdenMedica extends javax.swing.JDialog {

    /**
     * Creates new form DialogOrdenMedica
     */
    public DialogOrdenMedica(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblNombrep = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblApellidop = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblDocumentop = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblEps = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblTipoCita = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblTipoSangre = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblPeso = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblAltura = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblFechaCita = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        lblNombreMedico = new javax.swing.JLabel();
        lblEspecialidad = new javax.swing.JLabel();
        lblEspecialidadMedico = new javax.swing.JLabel();
        lbMedicamentos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lblReceta = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAReceta = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Nombre Paciente");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        lblNombrep.setText("jLabel2");
        jPanel1.add(lblNombrep, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, -1, -1));

        jLabel3.setText("Apellido Paciente");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        lblApellidop.setText("jLabel4");
        jPanel1.add(lblApellidop, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        jLabel5.setText("Documento Pciente");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        lblDocumentop.setText("jLabel6");
        jPanel1.add(lblDocumentop, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, -1, -1));

        jLabel7.setText("Gmail");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        lblEmail.setText("jLabel8");
        jPanel1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));

        jLabel9.setText("EPS");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        lblEps.setText("jLabel10");
        jPanel1.add(lblEps, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, -1, -1));

        jLabel2.setText("sexo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        lblSexo.setText("jLabel4");
        jPanel1.add(lblSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, -1));

        jLabel4.setText("Tipo Sangre");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        lblTipoCita.setText("jLabel6");
        jPanel1.add(lblTipoCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, -1, -1));

        jLabel6.setText("TipoCita");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, -1, -1));

        lblTipoSangre.setText("jLabel8");
        jPanel1.add(lblTipoSangre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, -1, -1));

        jLabel8.setText("peso");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, -1, -1));

        lblPeso.setText("jLabel10");
        jPanel1.add(lblPeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, -1));

        jLabel10.setText("Altura");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 150, -1, -1));

        lblAltura.setText("jLabel11");
        jPanel1.add(lblAltura, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, -1, -1));

        jLabel11.setText("fecha Cita");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, -1));

        lblFechaCita.setText("jLabel12");
        jPanel1.add(lblFechaCita, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, -1));

        jLabel12.setText("Hora Cita");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, -1, -1));

        lblHora.setText("jLabel13");
        jPanel1.add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 230, -1, -1));

        jLabel13.setText("Medico");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 280, -1, -1));

        lblNombreMedico.setText("jLabel14");
        jPanel1.add(lblNombreMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, -1, -1));

        lblEspecialidad.setText("Especialidad");
        jPanel1.add(lblEspecialidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 330, -1, -1));

        lblEspecialidadMedico.setText("jLabel14");
        jPanel1.add(lblEspecialidadMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, -1, -1));

        lbMedicamentos.setText("Medicamento");
        jPanel1.add(lbMedicamentos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 150, -1));

        lblReceta.setText("receta");
        jPanel1.add(lblReceta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        txtAReceta.setEditable(false);
        txtAReceta.setColumns(20);
        txtAReceta.setRows(5);
        jScrollPane2.setViewportView(txtAReceta);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        jLabel14.setText("Diagnostico");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, -1, -1));

        txtArea.setEditable(false);
        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane3.setViewportView(txtArea);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 550, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogOrdenMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogOrdenMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogOrdenMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogOrdenMedica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogOrdenMedica dialog = new DialogOrdenMedica(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbMedicamentos;
    private javax.swing.JLabel lblAltura;
    private javax.swing.JLabel lblApellidop;
    private javax.swing.JLabel lblDocumentop;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEps;
    private javax.swing.JLabel lblEspecialidad;
    private javax.swing.JLabel lblEspecialidadMedico;
    private javax.swing.JLabel lblFechaCita;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblNombreMedico;
    private javax.swing.JLabel lblNombrep;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lblReceta;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTipoCita;
    private javax.swing.JLabel lblTipoSangre;
    private javax.swing.JTextArea txtAReceta;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables
}
