/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package farmasalud.view;

import Controller.ControllerCargarMedicosCitas;
import Listener.EnfermedadSeleccionadaListener;
import dao.EnfermedadesDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author Maria liz
 */
public class Enfermedades extends javax.swing.JDialog {
   private EnfermedadSeleccionadaListener listener;
private EnfermedadesDAO enfermedadDAO = new EnfermedadesDAO();
ControllerCargarMedicosCitas controller = ControllerCargarMedicosCitas.getInstance();
private DialogAtender dialogAtender;

    public Enfermedades(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
controller.setTablaEnfermedades(tableEnfermedades);
controller.initTableEnfermedades();
controller.cargarDatosEnTabla();

    }
  public void setDialogAtender(DialogAtender dialogAtender) {
        this.dialogAtender = dialogAtender;
    }

    private void cargarDiagnosticoSeleccionado() {
        int fila = tableEnfermedades.getSelectedRow();
        if (fila >= 0) {
            String diagnostico = tableEnfermedades.getValueAt(fila, 1).toString();
            if (dialogAtender != null) {
                dialogAtender.setDiagnostico(diagnostico);
            }
        }
    }

    public void inicializarListener() {
        tableEnfermedades.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                cargarDiagnosticoSeleccionado();
            }
        });
    }

    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableEnfermedades = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtEnfermedades = new javax.swing.JTextField();
        btnEnfemedades = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnAgregarEnfermedad = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableEnfermedades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableEnfermedades);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 760, 370));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Enfermedad");

        txtEnfermedades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnfermedadesActionPerformed(evt);
            }
        });

        btnEnfemedades.setText("Buscar");
        btnEnfemedades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnfemedadesActionPerformed(evt);
            }
        });

        btnRefresh.setText("jButton1");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEnfermedades, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83)
                .addComponent(btnEnfemedades)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(btnRefresh)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                    .addComponent(txtEnfermedades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnfemedades)
                    .addComponent(btnRefresh))
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 750, 50));

        btnAgregarEnfermedad.setText("Agregar Enfermedad");
        btnAgregarEnfermedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarEnfermedadActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarEnfermedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 450, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnfemedadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnfemedadesActionPerformed
       String texto = txtEnfermedades.getText().trim();
    controller.buscarEnfermedadesPorNombre(texto);

    }//GEN-LAST:event_btnEnfemedadesActionPerformed

    private void txtEnfermedadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnfermedadesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnfermedadesActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
 controller.cargarDatosEnTabla();        // TODO add your handling code here:
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnAgregarEnfermedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarEnfermedadActionPerformed
   int fila = tableEnfermedades.getSelectedRow();
    if (fila >= 0) {
        String nombreEnfermedad = tableEnfermedades.getValueAt(fila, 1).toString(); 
        String sintomas = tableEnfermedades.getValueAt(fila, 3).toString();        

        String diagnosticoCompleto = "Enfermedad: " + nombreEnfermedad + "\nSíntomas: " + sintomas;

        if (dialogAtender != null) {
            dialogAtender.setDiagnostico(diagnosticoCompleto);
            this.dispose(); // Cierra el diálogo Enfermedades si ya seleccionó
        }
    } else {
        JOptionPane.showMessageDialog(this, "Seleccione una enfermedad.");
    }    
    }//GEN-LAST:event_btnAgregarEnfermedadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Enfermedades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Enfermedades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Enfermedades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Enfermedades.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Enfermedades dialog = new Enfermedades(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarEnfermedad;
    private javax.swing.JButton btnEnfemedades;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableEnfermedades;
    private javax.swing.JTextField txtEnfermedades;
    // End of variables declaration//GEN-END:variables
}
